export default {
    PRIMARY_COLOR: '#F4BF42',
    SECONDARY_COLOR: '#EA3358',
    THIRD_COLOR: '#EF89C3',
    FOURTH_COLOR: '#5DAFFA',
    FIFTH_COLOR: '#21AB38',
    SIXTH_COLOR: '#4269F4',
    FONT_SIZE_XS: 15,
    FONT_SIZE_S: 20,
    FONT_SIZE_M: 25,
    FONT_SIZE_L: 44,
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_MEDIUM: '500',
    FONT_WEIGHT_BOLD: '700',
    FONT_FAMILY: 'Roboto', 
    BACKGROUND_COLOR_LIGHT: '#f0f6f7',
    CONTAINER_PADDING: 20,
    TEXT_INPUT_PADDING: 10
  };